name: "GAR build/push/sign"
description: "Build, push, and sign (to Google Artifact Registry)"
inputs:
  dockerfile:
    description: "Dockerfile path"
    default: "Dockerfile"

  name:
    description: "Name of image"
    required: true

  google_service_account:
    description: "Name of google service account to impersonate"
    required: true

  push:
    description: "Wether or not to push image"
    default: true

  workload_identity_provider:
    description: "The workload identity provider for google service account impersonation"
    required: true

  registry:
    description: "The Google Artifact Registry path to push image to"
    default: "europe-north1-docker.pkg.dev/nais-io/nais/images"

outputs:
  tag: 
    description: "full image tag"
    value: ${{ fromJSON(steps.metadata.outputs.json).tags[0] }}
  version:
    description: "version"
    value: ${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}

runs:
  using: "composite"
  steps:
    - name: "Install cosign"
      uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 # ratchet:sigstore/cosign-installer@main
      with:
        cosign-release: "v2.0.0"

    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d" # ratchet:google-github-actions/auth@v1.0.0
      with:
        workload_identity_provider: "${{ inputs.workload_identity_provider }}"
        service_account: "${{ inputs.google_service_account }}@nais-io.iam.gserviceaccount.com"
        token_format: "access_token"

    - name: "Login to registry"
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # ratchet:docker/login-action@v2
      with:
        registry: "${{ inputs.registry }}"
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"

    - name: "Docker metadata"
      id: "metadata"
      uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # ratchet:docker/metadata-action@v4
      with:
        images: "${{ inputs.registry }}/${{ inputs.name }}"
        tags: |
          type=raw,value={{date 'YYYYMMDD-hhmmss' tz='Europe/Oslo'}}-{{sha}}
          type=raw,value=latest

    - name: "Build and push"
      id: "build_push"
      uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # ratchet:docker/build-push-action@v3
      with:
        context: .
        file: "${{ inputs.dockerfile }}"
        push: ${{ inputs.push }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

    - name: "Save image_ref to env"
      if: inputs.push
      shell: bash
      run: echo "image_ref=${{ inputs.registry }}/${{ inputs.name }}@${{ steps.build_push.outputs.digest }}" >> $GITHUB_ENV

    - name: "Sign image"
      if: inputs.push
      shell: bash
      run: cosign sign --yes "${{ env.image_ref }}"

    - name: Create SBOM
      if: inputs.push
      uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252 # ratchet:aquasecurity/trivy-action@master
      with:
        scan-type: "image"
        format: "cyclonedx"
        output: "cyclone.sbom.json"
        image-ref: "${{ env.image_ref }}"

    - name: Attest image
      if: inputs.push
      shell: bash
      run: |
        cosign attest --yes --predicate cyclone.sbom.json --type cyclonedx "${{ env.image_ref }}"
